const initForm={
  organizations:[
    {
      id:1,
      name:'Organization1',
      checked:true
    },
    {
      id:2,
      name:'Organization2',
      checked:false
    }
  ],
  taskOptions:[
    {
      id:1,
      name:'Block edit',
      checked:true
    },
    {
      id:2,
      name:'Action',
      checked:false
    },
    {
      id:3,
      name:'Repeat',
      checked:true
    },
    {
      id:4,
      name:'Restart last response',
      checked:false
    }
  ],
  customers:[
    {
      id:1,
      name:'customer1',
      checked:true
    },
    {
      id:2,
      name:'customer2',
      checked:false
    }
  ],
  products:[
    {
      id:1,
      name:'COMPOSITE FILTER',
      checked:true
    },
    {
      id:2,
      name:'RD SIDE STREAM',
      checked:false
    },
    {
      id:3,
      name:'P&C',
      checked:true
    },
    {
      id:4,
      name:'PRE FILTER',
      checked:false
    }
  ],
  users:[
    {
      id:1,
      name:'User1',
      checked:true
    },
    {
      id:2,
      name:'User2',
      checked:false
    },
    {
      id:3,
      name:'User3',
      checked:true
    }
  ],
  assignedOrganizations:[
    {
      id:1,
      name:'Organization1',
      checked:true
    },
    {
      id:2,
      name:'Organization2',
      checked:false
    }
  ],
  assignTypes:[
    {
      id:1,
      name:'Organization',
      checked:false
    },
    {
      id:2,
      name:'Users',
      checked:true
    }
  ],
  taskSubject:'linh kien (Composite Filter, RO Side Stream....)',
  description: 'my description here',
  status:[
    {
      id:1,
      name:'OPEN',
      checked:true
    },
    {
      id:2,
      name:'CLOSE',
      checked:false
    }
  ],
  actions:[
    {
      id:1,
      startDate:'10/09/2017 14:00',
      endDate:'10/09/2017 16:53',
      availableActions:[
        {
          id:1,
          name:'LẮP MỚI',
          checked:true
        },
        {
          id:2,
          name:'SỬA',
          checked:false
        }
      ],
    },
  ]
}
export default initForm
